### ISSUE TITLE
Empty .pak file after installing mods

### ISSUE THREAD

**Issue by RustyTrader** [Jimk72/Icarus_Software#2]
When I install a mod via the mod manager it is always empty, (0KB).
It seems it is capable of creating the .pak file but it contains nothing.
The Mod Manager show the files is created but it is empty.
![Screenshot 2022-10-11 072242](https://user-images.githubusercontent.com/110967/195003598-11fe2bfa-f7b9-42a7-8a81-8b043faa2b4b.png)
![Screenshot 2022-10-11 072135](https://user-images.githubusercontent.com/110967/195003603-4fb1e59a-3ee0-4ea2-9bbc-6e8de6db20b6.png)

**Comment by Rockstar04** [comment]
I am experiencing the same issue. Using version 0.8

**Comment by Rockstar04** [comment]
Version 0.9 seems to have resolved the issue.

@RustyTrader Can you try to replicate your issue with the latest version of the Mod Manager?

**Comment by Jimk72** [comment]
It was most likely the wrong version of unrealpak.exe. This is why I included it with my program. Almost every issue people were having was using the wrong version of unrealpak. So to help prevent that issue I included it.

**Comment by RustyTrader** [comment]
Tried 0.9 but got the same issue, had to point my Setting to the new Included unrealpak.exe and now it is working like a charm, thanks.
Please update the Install instructions to indicate that the unrealpak.exe is in the Mod manager folder

**Comment by Jimk72** [comment]
I’m in the process of setting up a video of how to install and use it.
