### ISSUE TITLE
Invalid date messsage

### ISSUE THREAD

**Issue by CelinaxCute** [Jimk72/Icarus_Software#7]
Its very annoy everytime i install a mod i need clicking 100times OK and then i can add new mod this is shitty and not well implemented pls add an enable disable to remove this

**Comment by Jimk72** [comment]
Are you using the latest version of IMM?

**Comment by CelinaxCute** [comment]
> Are you using the latest version of IMM?

Yeaaa i forget to press update because i think its latest i downloaded it from the site so yea thats why i closed it ^^

Greetings
